#!/bin/bash
# Quick Testing Commands for Payment System

echo "=== Payment System - Quick Test Commands ==="
echo ""
echo "1. CHECK DATABASE RECORDS:"
echo "   python3 manage.py shell << 'EOF'"
echo "   from rental.models import MonthlyPayment, PaymentRecord"
echo "   print(f'Payments: {MonthlyPayment.objects.count()}')"
echo "   print(f'Records: {PaymentRecord.objects.count()}')"
echo "   EOF"
echo ""
echo "2. CREATE A TEST PAYMENT:"
echo "   python3 manage.py shell << 'EOF'"
echo "   from rental.models import MonthlyPayment, Room"
echo "   from datetime import date"
echo "   room = Room.objects.first()"
echo "   p, _ = MonthlyPayment.objects.get_or_create("
echo "       room=room, month=date(2025,11,1),"
echo "       defaults={'rent_amount': 6000}"
echo "   )"
echo "   print(f'Payment {p.id} created for {room.number}')"
echo "   EOF"
echo ""
echo "3. CREATE A TEST PAYMENT RECORD:"
echo "   python3 manage.py shell << 'EOF'"
echo "   from rental.models import MonthlyPayment, PaymentRecord"
echo "   from django.contrib.auth.models import User"
echo "   from datetime import date"
echo "   p = MonthlyPayment.objects.first()"
echo "   u = User.objects.filter(is_staff=True).first()"
echo "   r = PaymentRecord.objects.create("
echo "       monthly_payment=p,"
echo "       payment_date=date(2025,11,14),"
echo "       payment_amount=3000,"
echo "       payment_method='cash',"
echo "       created_by=u"
echo "   )"
echo "   print(f'Record {r.id} created for {p.room.number} - {r.payment_date}')"
echo "   EOF"
echo ""
echo "4. UPDATE PAYMENT STATUS:"
echo "   python3 manage.py shell << 'EOF'"
echo "   from rental.models import MonthlyPayment"
echo "   p = MonthlyPayment.objects.first()"
echo "   p.paid_amount += 3000"
echo "   if p.paid_amount >= p.rent_amount:"
echo "       p.payment_status = 'paid'"
echo "   else:"
echo "       p.payment_status = 'partial'"
echo "   p.save()"
echo "   print(f'{p.room.number}: ₹{p.paid_amount}/{p.rent_amount} ({p.payment_status})')"
echo "   EOF"
echo ""
echo "5. VIEW ALL PAYMENT RECORDS:"
echo "   python3 manage.py shell << 'EOF'"
echo "   from rental.models import PaymentRecord"
echo "   for rec in PaymentRecord.objects.all():"
echo "       print(f'{rec.payment_date}: ₹{rec.payment_amount} ({rec.payment_method})')"
echo "   EOF"
echo ""
echo "6. RUN SERVER WITH DEBUGGING:"
echo "   python3 manage.py runserver 0.0.0.0:8000"
echo "   Then open browser DevTools (F12) → Console"
echo "   Submit a form and check console output"
echo ""
echo "7. ADMIN PANEL:"
echo "   http://localhost:8000/admin/"
echo "   Look in 'Monthly Payments' and 'Payment Records'"
echo ""
echo "8. PAYMENT MANAGEMENT PAGE:"
echo "   http://localhost:8000/manage-payments/"
echo ""
