# Generated by Django 5.2.5 on 2025-11-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_monthlypayment_paymentrecord_electricitybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='document_verification_image',
            field=models.ImageField(blank=True, help_text='Document verification image', null=True, upload_to='document_verification/'),
        ),
        migrations.AddField(
            model_name='guest',
            name='id_proof_image',
            field=models.ImageField(blank=True, help_text='Photo of ID document', null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='guest',
            name='lpu_id',
            field=models.CharField(blank=True, help_text='LPU ID or Student ID', max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='lpu_id_photo',
            field=models.ImageField(blank=True, help_text='Photo of LPU ID', null=True, upload_to='lpu_ids/'),
        ),
    ]
