# Generated by Django 5.2.5 on 2025-12-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_guest_document_verification_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(help_text='e.g., M1, 1, 2, etc.', max_length=50)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('painting', 'Painting'), ('carpentry', 'Carpentry'), ('cleaning', 'Cleaning'), ('repairs', 'General Repairs'), ('security', 'Security'), ('internet', 'Internet/WiFi'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('is_paid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
