# Generated by Django 5.2.5 on 2025-12-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_maintenanceexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='id_proof_image',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='lpu_id',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='lpu_id_photo',
        ),
        migrations.AddField(
            model_name='guest',
            name='college_id',
            field=models.CharField(blank=True, help_text='College ID or Student ID', max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='college_id_photo',
            field=models.ImageField(blank=True, help_text='Photo of College ID', null=True, upload_to='college_ids/'),
        ),
        migrations.AddField(
            model_name='guest',
            name='govt_id_photo',
            field=models.ImageField(blank=True, help_text='Photo of Government ID document', null=True, upload_to='govt_ids/'),
        ),
        migrations.AddField(
            model_name='guest',
            name='student_college',
            field=models.CharField(blank=True, help_text='Name of the college/university', max_length=100),
        ),
    ]
