"""Add agreed_rent field to Room

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_remove_guest_id_proof_image_remove_guest_lpu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='agreed_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-room negotiated rent (overrides price when set)', max_digits=8, null=True),
        ),
    ]
