# Generated by Django 5.2.5 on 2026-01-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_guest_email_alter_guest_phone'),
    ]

    def delete_building_6_rooms(apps, schema_editor):
        Room = apps.get_model('rental', 'Room')
        Room.objects.filter(number__startswith='G-').delete()

    operations = [
        migrations.RunPython(delete_building_6_rooms),
    ]
