# Generated by Django 5.2.5 on 2026-01-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_delete_building_6_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of tenants allowed in this room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Manual override for room availability'),
        ),
    ]
