# Generated by Django 5.2.5 on 2026-01-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_room_capacity_alter_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=2, help_text='Maximum number of tenants allowed in this room (max 2)'),
        ),
    ]
