# Generated by Django 5.2.5 on 2026-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_data_cap_capacities'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='occupancy_preference',
            field=models.CharField(choices=[('single', 'Single (Private Room)'), ('double', 'Double (Shared Room)')], default='double', help_text="Tenant's occupancy preference - defaults to double occupancy", max_length=10),
        ),
    ]
