# Generated by Django 5.2.5 on 2026-02-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_guest_occupancy_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='aadhar_back',
            field=models.ImageField(blank=True, help_text='Aadhar Card Back Side', null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='guest',
            name='aadhar_front',
            field=models.ImageField(blank=True, help_text='Aadhar Card Front Side', null=True, upload_to='aadhar_cards/'),
        ),
    ]
