# Generated by Django 5.2.5 on 2026-09-22 16:39

import django.db.models.deletion
from django.db import migrations, models


BUILDING_NAMES = {
    'A': 'M1 Complex',
    'B': 'Building 1',
    'C': 'Building 2',
    'D': 'Building 3',
    'E': 'Building 4',
    'F': 'Building 5',
}


def backfill_buildings(apps, schema_editor):
    Building = apps.get_model('rental', 'Building')
    Room = apps.get_model('rental', 'Room')
    prefixes = set()
    for room in Room.objects.all().only('id', 'number'):
        prefix = room.number.split('-', 1)[0] if '-' in room.number else room.number[:1]
        if prefix:
            prefixes.add(prefix)
    for prefix in sorted(prefixes):
        building, _ = Building.objects.get_or_create(
            code=prefix,
            defaults={'name': BUILDING_NAMES.get(prefix, f'Building {prefix}')},
        )
        Room.objects.filter(number__startswith=f'{prefix}-').update(building_id=building.id)
        Room.objects.filter(number=prefix).update(building_id=building.id)


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_guest_aadhar_back_guest_aadhar_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rental.building'),
        ),
        migrations.RunPython(backfill_buildings, migrations.RunPython.noop),
    ]
