from django.urls import path
from . import views
from .performance_views import (
    performance_dashboard, 
    record_payment_from_dashboard,
    record_bill_payment_from_dashboard,
    record_maintenance,
)

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('health/', views.health_check, name='health_check'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('booking/', views.booking_page, name='booking_page'),
    path('manage-buildings/', views.manage_buildings, name='manage_buildings'),
    path('manage-guests/', views.manage_guests, name='manage_guests'),
    path('manage-payments/', views.manage_payments, name='manage_payments'),
    path('manage-electricity-bills/', views.manage_electricity_bills, name='manage_electricity_bills'),
    path('performance-dashboard/', performance_dashboard, name='performance_dashboard'),
    path('api/guests/', views.get_guests, name='get_guests'),
    path('api/guest/add/', views.add_guest, name='add_guest'),
    path('api/guest/<int:guest_id>/update/', views.update_guest, name='update_guest'),
    path('api/guest/<int:guest_id>/checkout/', views.checkout_guest, name='checkout_guest'),
    path('api/guest/<int:guest_id>/delete/', views.delete_guest, name='delete_guest'),
    # Restore original and add new
    path('api/available-rooms/', views.get_available_rooms, name='get_available_rooms'),
    path('api/submit-booking/', views.submit_booking, name='submit_booking'),
    path('api/room/<int:room_id>/update/', views.update_room, name='update_room'),
    path('api/room/add/', views.add_room, name='add_room'),
    path('api/room/<int:room_id>/delete/', views.delete_room, name='delete_room'),
    path('api/room/<int:room_id>/details/', views.get_room_details, name='get_room_details'),
    path('api/payment/create-monthly/', views.create_monthly_payment, name='create_monthly_payment'),
    path('api/payment/record/', views.record_payment, name='record_payment'),
    path('api/payment/record-from-dashboard/', record_payment_from_dashboard, name='record_payment_dashboard'),
    path('api/payment/record-bill-from-dashboard/', record_bill_payment_from_dashboard, name='record_bill_payment_dashboard'),
    path('api/maintenance/record/', record_maintenance, name='record_maintenance'),
    path('api/electricity/bill/add/', views.create_electricity_bill, name='create_electricity_bill'),
    path('api/electricity/payment/record/', views.record_electricity_payment, name='record_electricity_payment'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('api/user/add/', views.add_user, name='add_user'),
    path('api/user/<int:user_id>/update/', views.update_user, name='update_user'),
    path('api/user/<int:user_id>/delete/', views.delete_user, name='delete_user'),
    path('api/room/<int:room_id>/tenants/', views.get_room_tenants, name='get_room_tenants'),
    path('api/room/<int:room_id>/payment-history/', views.get_payment_history, name='get_payment_history'),
    path('api/room/<int:room_id>/electricity-history/', views.get_electricity_history, name='get_electricity_history'),
    path('api/payment-record/<int:record_id>/update/', views.update_payment_record, name='update_payment_record'),
    path('api/payment-record/<int:record_id>/delete/', views.delete_payment_record, name='delete_payment_record'),
]
